cargo-features = ["default-run"]

[package]
name = "fwop"
version = "0.1.0"
authors = ["C Jones <code@calebjones.net>"]
edition = "2018"
default-run = "solve"

[dependencies]

[dev-dependencies]
criterion = "0.2"
proptest = "0.7"

[[bench]]
name = "blit"
harness = false